CREATE TABLE Reviews (
    id TEXT PRIMARY KEY,
    typename TEXT,
    attendanceMandatory TEXT,
    clarityRating INTEGER,
    class TEXT,
    comment TEXT,
    createdByUser BOOLEAN,
    date TEXT,
    difficultyRating INTEGER,
    flagStatus TEXT,
    grade TEXT,
    helpfulRating INTEGER,
    isForCredit BOOLEAN,
    isForOnlineClass BOOLEAN,
    legacyId INTEGER,
    ratingTags TEXT,
    teacherNote TEXT,
    textbookUse INTEGER,
    thumbsDownTotal INTEGER,
    thumbsUpTotal INTEGER,
    wouldTakeAgain INTEGER,
    teacherId TEXT,
    FOREIGN KEY (teacherId) REFERENCES Teachers(id)
);